#### Exercises for Julia and JuMP Tutorials

After you have gone through the tutorial, you should be able to fill in these simple exercises. To submit your reponse, please take the following steps: 
1. Make sure to run all the cells (such that we can see the output that you create).
2. Print a pdf of the notebook (make sure that it is easily readable).
3. Upload the pdf to Canvas by **Friday February 4**.

### Exercises

#### 1.0

Get started by reading the following statements about your work and signing that you agree by typing your name:

1. I have read and understood the homework information available on Canvas (https://canvas.wisc.edu/courses/192244/pages/homework-information)

2. You are encouraged to discuss homework problems with classmates and even work in groups. However, **the work you turn in must be your own**, and not copied from others. 

3. PLAGIARISM AND OTHER TYPES OF ACADEMIC MISCONDUCT IS NOT TOLERATED AND WILL HAVE CONSEQUENCES. 

SIGNATURE: Kyle Yeo

#### 1.1 Finding help

Look up docs for the function `convert`.

In [1]:
?convert

search: convert ConcurrencyViolationError code_native @code_native



```
convert(T, x)
```

Convert `x` to a value of type `T`.

If `T` is an [`Integer`](@ref) type, an [`InexactError`](@ref) will be raised if `x` is not representable by `T`, for example if `x` is not integer-valued, or is outside the range supported by `T`.

# Examples

```jldoctest
julia> convert(Int, 3.0)
3

julia> convert(Int, 3.5)
ERROR: InexactError: Int64(3.5)
Stacktrace:
[...]
```

If `T` is a [`AbstractFloat`](@ref) or [`Rational`](@ref) type, then it will return the closest value to `x` representable by `T`.

```jldoctest
julia> x = 1/3
0.3333333333333333

julia> convert(Float32, x)
0.33333334f0

julia> convert(Rational{Int32}, x)
1//3

julia> convert(Rational{Int64}, x)
6004799503160661//18014398509481984
```

If `T` is a collection type and `x` a collection, the result of `convert(T, x)` may alias all or part of `x`.

```jldoctest
julia> x = Int[1, 2, 3];

julia> y = convert(Vector{Int}, x);

julia> y === x
true
```

See also: [`round`](@ref), [`trunc`](@ref), [`oftype`](@ref), [`reinterpret`](@ref).


#### 1.2 Assigning variables, checking and converting types
Assign `365` to a variable named `days`. 

In [2]:
days = 365

365

Use the `convert` function to change the variable `days` from an integer to a float, and assign it to a new variable `days_float`. 

In [3]:
days_float = convert(Float32, days)

365.0f0

Check whether the types of `days` and `days_float` are the same.

In [4]:
typeof(days) == typeof(days_float)

false

#### 1.3 Working with arrays and tuples

Define the array 

`square = [1, 2, 3]` 

and the tuple

`round = (4,5,6)`

In [5]:
square = [1,2,3]
round = (4,5,6);

Access the first element of the array and the tuple, and add them together. 

In [6]:
square[1] + round[1]

5

Change the first element of the array to be equal to the first element of the tuple.

In [7]:
square[1] = round[1]
square

3-element Vector{Int64}:
 4
 2
 3

Try to change the third element of the tuple to be equal to that of the array.

Why will this not work?

In [8]:
round[3] = array[3]
# This will not work, because tuples are immutable

LoadError: UndefVarError: array not defined

#### 1.4 Dictionaries

Create a dictionary which lists three of your favorite restaurants and their ranking (1, 2 or 3).

In [9]:
res_dic = Dict("Chipotle" => 1, "Mooyah" => 2, "Ramenkid" => 3)
res_dic

Dict{String, Int64} with 3 entries:
  "Mooyah"   => 2
  "Ramenkid" => 3
  "Chipotle" => 1

#### 1.5 Matrix (two-dimension arrays)
Create the following matrix: $$B = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

In [10]:
B = [1 2 1; 3 0 1; 0 2 4]

3×3 Matrix{Int64}:
 1  2  1
 3  0  1
 0  2  4

Change the first element in the first row of B into 5, and check if it is an even number. (Tip: Use "a%b == c", which means the remainder of a/b is c)

In [11]:
B[1,1] = 5
B[1,1] % 2 == 0

false

#### 1.6 Some basic math


Check if 5 is an even number. (Tip: Use the modulo operation "a%b == c", which means the remainder of a/b is c)

In [12]:
5 % 2 == 0

false

#### 1.7 For loops

Write a for loop to print the integers from 1 to 5.

In [13]:
for i in 1:5
    println(i)
end

1
2
3
4
5


Now write a for loop to go through every element in the above matrix, check if it is odd. If it is, then add 1 to that element. And print your matrix. 

In [14]:
for i in 1:3
    for j in 1:3
        if B[i,j] % 2 != 0
            B[i,j] += 1
        end
    end
end
    
B

3×3 Matrix{Int64}:
 6  2  2
 4  0  2
 0  2  4

#### 1.8 Functions
Write a function called `my_func` which takes a number as an input, and return an array containing integers from 1 to $n$. And try your function with input 5.

In [15]:
function my_func(n)
    return [i for i in 1:n]
end
    

println(my_func(5))

[1, 2, 3, 4, 5]


What happens to the output if you insted use the input 5.5 (which is a non-integer)?

In [16]:
println(my_func(5.5))

#= 
The difference between the output of my_func(5) and my_func(5.5) is the type of elements in the array (int => float)

=#

[1.0, 2.0, 3.0, 4.0, 5.0]


Now slightly modify your function, and create a new function `odd` which outputs an array of all the odd numbers in [1,$n$]. Test your function with input 7.

In [17]:
function odd(n)
    return [i for i in 1:n if i % 2 != 0]
end

odd(7)

4-element Vector{Int64}:
 1
 3
 5
 7

#### 1.9 JuMP Model

Consider the Top Brass model problem. How does the problem formulation and optimal solution change if you have to sell at produce at least 400 pre-ordered brass football trophies, and you only have 3000 board feet of wood? Implement this new Top Brass model below.

In [1]:
using Pkg
using Clp
using JuMP
using Ipopt
using Cbc

m = Model()

@variable(m, 400 <= f <= 1000)           # football trophies
@variable(m, 0 <= s <= 1500)           # soccer trophies
@constraint(m, 4*f + 2*s <= 3000)        # total board feet of wood
@constraint(m, f + s <= 1750)          # total number of plaques
@objective(m, Max, 12*f + 9*s)          # maximize profit


12 f + 9 s

What is the optimal solution to this new instance of the Top Brass problem?

In [2]:
set_optimizer(m, with_optimizer(Ipopt.Optimizer))

#solve
@time optimize!(m)
f_value = value(f)
s_value = value(s)
obj_value = objective_value(m)

println("The optimal number of footballs ", f_value)
println("The optimal number of soccer ", s_value)
println("The objecvtive value is ", obj_value)


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        2
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality co